# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              https://whatthecole.github.io/lx/
encoding:         UTF-8
